name: kalorikuplus
description: Aplikasi tracker kalori dan hidup sehat

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3


  # Firebase (Auth + Realtime Database)
  firebase_core: ^3.4.1
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.0
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
