class FoodItem {
  final String id;
  final String name;
  final String emoji;
  final double calories;
  final double carbs;
  final double protein;
  final double fat;
  final String category;

  const FoodItem({
    required this.id,
    required this.name,
    required this.emoji,
    required this.calories,
    required this.carbs,
    required this.protein,
    required this.fat,
    required this.category,
  });
}

class FoodLog {
  final String id;
  final FoodItem food;
  final double servings;
  final String mealType; // breakfast, lunch, dinner, snack
  final DateTime loggedAt;

  FoodLog({
    required this.id,
    required this.food,
    required this.servings,
    required this.mealType,
    required this.loggedAt,
  });

  double get totalCalories => food.calories * servings;
  double get totalCarbs => food.carbs * servings;
  double get totalProtein => food.protein * servings;
  double get totalFat => food.fat * servings;
}

class WaterLog {
  final DateTime loggedAt;
  final int glasses; // total glasses for the day

  WaterLog({required this.loggedAt, required this.glasses});
}

// Database makanan Indonesia
final List<FoodItem> foodDatabase = [
  const FoodItem(
      id: '1',
      name: 'Nasi Putih',
      emoji: '🍚',
      calories: 260,
      carbs: 57,
      protein: 4.4,
      fat: 0.4,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '2',
      name: 'Nasi Merah',
      emoji: '🍚',
      calories: 218,
      carbs: 46,
      protein: 4.5,
      fat: 1.6,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '3',
      name: 'Ayam Panggang',
      emoji: '🍗',
      calories: 165,
      carbs: 0,
      protein: 31,
      fat: 3.6,
      category: 'Protein'),
  const FoodItem(
      id: '4',
      name: 'Ayam Goreng',
      emoji: '🍗',
      calories: 246,
      carbs: 7.8,
      protein: 28,
      fat: 12,
      category: 'Protein'),
  const FoodItem(
      id: '5',
      name: 'Telur Rebus',
      emoji: '🥚',
      calories: 78,
      carbs: 0.6,
      protein: 6.3,
      fat: 5.3,
      category: 'Protein'),
  const FoodItem(
      id: '6',
      name: 'Tempe Goreng',
      emoji: '🫘',
      calories: 160,
      carbs: 8,
      protein: 11,
      fat: 9,
      category: 'Protein'),
  const FoodItem(
      id: '7',
      name: 'Tahu Goreng',
      emoji: '🫘',
      calories: 120,
      carbs: 4,
      protein: 8,
      fat: 8,
      category: 'Protein'),
  const FoodItem(
      id: '8',
      name: 'Ikan Bakar',
      emoji: '🐟',
      calories: 140,
      carbs: 0,
      protein: 26,
      fat: 3,
      category: 'Protein'),
  const FoodItem(
      id: '9',
      name: 'Sayur Bayam',
      emoji: '🥬',
      calories: 23,
      carbs: 3.6,
      protein: 2.9,
      fat: 0.4,
      category: 'Sayuran'),
  const FoodItem(
      id: '10',
      name: 'Salad Sayur',
      emoji: '🥗',
      calories: 65,
      carbs: 11,
      protein: 2,
      fat: 2,
      category: 'Sayuran'),
  const FoodItem(
      id: '11',
      name: 'Pisang',
      emoji: '🍌',
      calories: 89,
      carbs: 23,
      protein: 1.1,
      fat: 0.3,
      category: 'Buah'),
  const FoodItem(
      id: '12',
      name: 'Apel',
      emoji: '🍎',
      calories: 52,
      carbs: 14,
      protein: 0.3,
      fat: 0.2,
      category: 'Buah'),
  const FoodItem(
      id: '13',
      name: 'Pepaya',
      emoji: '🍈',
      calories: 43,
      carbs: 11,
      protein: 0.5,
      fat: 0.3,
      category: 'Buah'),
  const FoodItem(
      id: '14',
      name: 'Oatmeal',
      emoji: '🥣',
      calories: 150,
      carbs: 27,
      protein: 5,
      fat: 2.5,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '15',
      name: 'Susu Sapi',
      emoji: '🥛',
      calories: 122,
      carbs: 11.7,
      protein: 8.1,
      fat: 4.8,
      category: 'Minuman'),
  const FoodItem(
      id: '16',
      name: 'Kacang Almond',
      emoji: '🌰',
      calories: 164,
      carbs: 6,
      protein: 6,
      fat: 14,
      category: 'Snack'),
  const FoodItem(
      id: '17',
      name: 'Mie Goreng',
      emoji: '🍜',
      calories: 380,
      carbs: 52,
      protein: 10,
      fat: 15,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '18',
      name: 'Gado-gado',
      emoji: '🥙',
      calories: 350,
      carbs: 30,
      protein: 14,
      fat: 18,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '19',
      name: 'Soto Ayam',
      emoji: '🍲',
      calories: 220,
      carbs: 18,
      protein: 18,
      fat: 8,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '20',
      name: 'Roti Gandum',
      emoji: '🍞',
      calories: 69,
      carbs: 13,
      protein: 3.6,
      fat: 1,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '21',
      name: 'Rendang Sapi',
      emoji: '🍛',
      calories: 195,
      carbs: 0.4,
      protein: 22.6,
      fat: 11,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '22',
      name: 'Sate Ayam',
      emoji: '🍢',
      calories: 300,
      carbs: 15,
      protein: 25,
      fat: 14,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '23',
      name: 'Bakso Sapi',
      emoji: '🍲',
      calories: 280,
      carbs: 22,
      protein: 16,
      fat: 13,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '24',
      name: 'Martabak Telur',
      emoji: '🍳',
      calories: 320,
      carbs: 20,
      protein: 15,
      fat: 21,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '25',
      name: 'Martabak Manis',
      emoji: '🥞',
      calories: 450,
      carbs: 65,
      protein: 8,
      fat: 18,
      category: 'Snack'),
  const FoodItem(
      id: '26',
      name: 'Jus Alpukat',
      emoji: '🥑',
      calories: 180,
      carbs: 22,
      protein: 2,
      fat: 10,
      category: 'Minuman'),
  const FoodItem(
      id: '27',
      name: 'Nasi Uduk',
      emoji: '🍛',
      calories: 290,
      carbs: 45,
      protein: 6,
      fat: 9,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '28',
      name: 'Pempek Palembang',
      emoji: '🐟',
      calories: 240,
      carbs: 28,
      protein: 12,
      fat: 8,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '29',
      name: 'Telur Dadar',
      emoji: '🍳',
      calories: 93,
      carbs: 0.4,
      protein: 6.5,
      fat: 7.3,
      category: 'Protein'),
  const FoodItem(
      id: '30',
      name: 'Jeruk',
      emoji: '🍊',
      calories: 47,
      carbs: 12,
      protein: 0.9,
      fat: 0.1,
      category: 'Buah'),
  const FoodItem(
      id: '31',
      name: 'Semangka',
      emoji: '🍉',
      calories: 30,
      carbs: 8,
      protein: 0.6,
      fat: 0.2,
      category: 'Buah'),
  const FoodItem(
      id: '32',
      name: 'Kopi Hitam',
      emoji: '☕',
      calories: 2,
      carbs: 0,
      protein: 0.2,
      fat: 0,
      category: 'Minuman'),
  const FoodItem(
      id: '33',
      name: 'Teh Manis',
      emoji: '🍵',
      calories: 70,
      carbs: 18,
      protein: 0,
      fat: 0,
      category: 'Minuman'),
  const FoodItem(
      id: '34',
      name: 'Salad Buah',
      emoji: '🥗',
      calories: 120,
      carbs: 20,
      protein: 1.5,
      fat: 4.5,
      category: 'Buah'),
  const FoodItem(
      id: '35',
      name: 'Bubur Ayam',
      emoji: '🥣',
      calories: 155,
      carbs: 24,
      protein: 7,
      fat: 3.5,
      category: 'Makanan Berat'),

  // ---- Tambahan makanan baru ----
  // Karbohidrat
  const FoodItem(
      id: '36',
      name: 'Nasi Goreng',
      emoji: '🍳',
      calories: 390,
      carbs: 54,
      protein: 10,
      fat: 14,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '37',
      name: 'Lontong',
      emoji: '🍚',
      calories: 127,
      carbs: 28,
      protein: 2.5,
      fat: 0.3,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '38',
      name: 'Roti Tawar Putih',
      emoji: '🍞',
      calories: 79,
      carbs: 15,
      protein: 2.7,
      fat: 1,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '39',
      name: 'Singkong Rebus',
      emoji: '🫚',
      calories: 160,
      carbs: 38,
      protein: 1.4,
      fat: 0.3,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '40',
      name: 'Kentang Rebus',
      emoji: '🥔',
      calories: 87,
      carbs: 20,
      protein: 1.9,
      fat: 0.1,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '41',
      name: 'Kentang Goreng',
      emoji: '🍟',
      calories: 312,
      carbs: 41,
      protein: 3.4,
      fat: 15,
      category: 'Karbohidrat'),
  const FoodItem(
      id: '42',
      name: 'Mie Rebus',
      emoji: '🍜',
      calories: 180,
      carbs: 34,
      protein: 6,
      fat: 2.5,
      category: 'Karbohidrat'),

  // Protein
  const FoodItem(
      id: '43',
      name: 'Daging Sapi',
      emoji: '🥩',
      calories: 218,
      carbs: 0,
      protein: 26,
      fat: 12,
      category: 'Protein'),
  const FoodItem(
      id: '44',
      name: 'Udang Rebus',
      emoji: '🦐',
      calories: 84,
      carbs: 0,
      protein: 18,
      fat: 0.9,
      category: 'Protein'),
  const FoodItem(
      id: '45',
      name: 'Cumi-cumi',
      emoji: '🦑',
      calories: 92,
      carbs: 3.1,
      protein: 15.6,
      fat: 1.4,
      category: 'Protein'),
  const FoodItem(
      id: '46',
      name: 'Ikan Salmon',
      emoji: '🐟',
      calories: 206,
      carbs: 0,
      protein: 28,
      fat: 10,
      category: 'Protein'),
  const FoodItem(
      id: '47',
      name: 'Ikan Tuna Kaleng',
      emoji: '🐟',
      calories: 109,
      carbs: 0,
      protein: 24,
      fat: 1,
      category: 'Protein'),
  const FoodItem(
      id: '48',
      name: 'Keju Slice',
      emoji: '🧀',
      calories: 113,
      carbs: 0.4,
      protein: 7,
      fat: 9.3,
      category: 'Protein'),
  const FoodItem(
      id: '49',
      name: 'Yogurt Plain',
      emoji: '🍶',
      calories: 60,
      carbs: 5.5,
      protein: 5.7,
      fat: 1.6,
      category: 'Protein'),

  // Sayuran
  const FoodItem(
      id: '50',
      name: 'Brokoli Kukus',
      emoji: '🥦',
      calories: 34,
      carbs: 7,
      protein: 2.8,
      fat: 0.4,
      category: 'Sayuran'),
  const FoodItem(
      id: '51',
      name: 'Wortel',
      emoji: '🥕',
      calories: 41,
      carbs: 10,
      protein: 0.9,
      fat: 0.2,
      category: 'Sayuran'),
  const FoodItem(
      id: '52',
      name: 'Kangkung Tumis',
      emoji: '🥬',
      calories: 35,
      carbs: 4,
      protein: 2.5,
      fat: 1.5,
      category: 'Sayuran'),
  const FoodItem(
      id: '53',
      name: 'Tomat',
      emoji: '🍅',
      calories: 18,
      carbs: 3.9,
      protein: 0.9,
      fat: 0.2,
      category: 'Sayuran'),
  const FoodItem(
      id: '54',
      name: 'Timun',
      emoji: '🥒',
      calories: 16,
      carbs: 3.6,
      protein: 0.7,
      fat: 0.1,
      category: 'Sayuran'),
  const FoodItem(
      id: '55',
      name: 'Kacang Panjang',
      emoji: '🫛',
      calories: 47,
      carbs: 8.4,
      protein: 2.8,
      fat: 0.4,
      category: 'Sayuran'),

  // Buah
  const FoodItem(
      id: '56',
      name: 'Mangga',
      emoji: '🥭',
      calories: 60,
      carbs: 15,
      protein: 0.8,
      fat: 0.4,
      category: 'Buah'),
  const FoodItem(
      id: '57',
      name: 'Anggur',
      emoji: '🍇',
      calories: 69,
      carbs: 18,
      protein: 0.7,
      fat: 0.2,
      category: 'Buah'),
  const FoodItem(
      id: '58',
      name: 'Melon',
      emoji: '🍈',
      calories: 34,
      carbs: 8,
      protein: 0.8,
      fat: 0.2,
      category: 'Buah'),
  const FoodItem(
      id: '59',
      name: 'Strawberry',
      emoji: '🍓',
      calories: 33,
      carbs: 8,
      protein: 0.7,
      fat: 0.3,
      category: 'Buah'),
  const FoodItem(
      id: '60',
      name: 'Alpukat',
      emoji: '🥑',
      calories: 160,
      carbs: 9,
      protein: 2,
      fat: 15,
      category: 'Buah'),
  const FoodItem(
      id: '61',
      name: 'Nanas',
      emoji: '🍍',
      calories: 50,
      carbs: 13,
      protein: 0.5,
      fat: 0.1,
      category: 'Buah'),
  const FoodItem(
      id: '62',
      name: 'Kelapa Muda',
      emoji: '🥥',
      calories: 45,
      carbs: 11,
      protein: 0.5,
      fat: 0.5,
      category: 'Buah'),

  // Snack
  const FoodItem(
      id: '63',
      name: 'Pisang Goreng',
      emoji: '🍌',
      calories: 172,
      carbs: 28,
      protein: 1.5,
      fat: 6.5,
      category: 'Snack'),
  const FoodItem(
      id: '64',
      name: 'Kripik Singkong',
      emoji: '🍿',
      calories: 230,
      carbs: 40,
      protein: 1.5,
      fat: 7,
      category: 'Snack'),
  const FoodItem(
      id: '65',
      name: 'Biskuit Marie',
      emoji: '🍪',
      calories: 130,
      carbs: 23,
      protein: 2,
      fat: 3.5,
      category: 'Snack'),
  const FoodItem(
      id: '66',
      name: 'Keripik Tempe',
      emoji: '🫘',
      calories: 200,
      carbs: 18,
      protein: 12,
      fat: 9,
      category: 'Snack'),
  const FoodItem(
      id: '67',
      name: 'Ubi Goreng',
      emoji: '🍠',
      calories: 148,
      carbs: 30,
      protein: 1.5,
      fat: 2.5,
      category: 'Snack'),
  const FoodItem(
      id: '68',
      name: 'Onde-onde',
      emoji: '🟡',
      calories: 150,
      carbs: 24,
      protein: 3,
      fat: 5,
      category: 'Snack'),
  const FoodItem(
      id: '69',
      name: 'Coklat Batang',
      emoji: '🍫',
      calories: 167,
      carbs: 19,
      protein: 1.5,
      fat: 10,
      category: 'Snack'),
  const FoodItem(
      id: '70',
      name: 'Kacang Tanah Goreng',
      emoji: '🥜',
      calories: 170,
      carbs: 5,
      protein: 7.3,
      fat: 14.7,
      category: 'Snack'),

  // Minuman
  const FoodItem(
      id: '71',
      name: 'Es Teh Manis',
      emoji: '🧊',
      calories: 70,
      carbs: 18,
      protein: 0,
      fat: 0,
      category: 'Minuman'),
  const FoodItem(
      id: '72',
      name: 'Jus Jeruk',
      emoji: '🍊',
      calories: 110,
      carbs: 26,
      protein: 1.7,
      fat: 0.5,
      category: 'Minuman'),
  const FoodItem(
      id: '73',
      name: 'Susu Kedelai',
      emoji: '🥛',
      calories: 80,
      carbs: 8,
      protein: 6,
      fat: 3,
      category: 'Minuman'),
  const FoodItem(
      id: '74',
      name: 'Es Cincau',
      emoji: '🧋',
      calories: 90,
      carbs: 22,
      protein: 1,
      fat: 0.5,
      category: 'Minuman'),
  const FoodItem(
      id: '75',
      name: 'Kopi Susu',
      emoji: '☕',
      calories: 100,
      carbs: 12,
      protein: 2.5,
      fat: 4.5,
      category: 'Minuman'),
  const FoodItem(
      id: '76',
      name: 'Es Kelapa Muda',
      emoji: '🥥',
      calories: 46,
      carbs: 11,
      protein: 0.5,
      fat: 0.5,
      category: 'Minuman'),
  const FoodItem(
      id: '77',
      name: 'Smoothie Pisang',
      emoji: '🥤',
      calories: 150,
      carbs: 30,
      protein: 4,
      fat: 2,
      category: 'Minuman'),

  // Makanan Berat (Tambahan)
  const FoodItem(
      id: '78',
      name: 'Rawon',
      emoji: '🍲',
      calories: 280,
      carbs: 15,
      protein: 22,
      fat: 14,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '79',
      name: 'Opor Ayam',
      emoji: '🍛',
      calories: 310,
      carbs: 8,
      protein: 24,
      fat: 21,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '80',
      name: 'Nasi Padang',
      emoji: '🍛',
      calories: 570,
      carbs: 65,
      protein: 28,
      fat: 22,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '81',
      name: 'Lontong Sayur',
      emoji: '🥙',
      calories: 240,
      carbs: 38,
      protein: 8,
      fat: 7,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '82',
      name: 'Nasi Kuning',
      emoji: '🍚',
      calories: 280,
      carbs: 48,
      protein: 5,
      fat: 7,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '83',
      name: 'Ketoprak',
      emoji: '🥙',
      calories: 320,
      carbs: 42,
      protein: 12,
      fat: 12,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '84',
      name: 'Siomay',
      emoji: '🥟',
      calories: 270,
      carbs: 22,
      protein: 18,
      fat: 12,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '85',
      name: 'Cap Cai',
      emoji: '🥘',
      calories: 120,
      carbs: 12,
      protein: 9,
      fat: 5,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '86',
      name: 'Nasi Tim Ayam',
      emoji: '🍚',
      calories: 220,
      carbs: 36,
      protein: 12,
      fat: 4,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '87',
      name: 'Pecel Lele',
      emoji: '🐟',
      calories: 350,
      carbs: 28,
      protein: 24,
      fat: 16,
      category: 'Makanan Berat'),
  const FoodItem(
      id: '88',
      name: 'Rujak Buah',
      emoji: '🥗',
      calories: 90,
      carbs: 22,
      protein: 1.5,
      fat: 0.5,
      category: 'Buah'),
];
